server:
  port: 8889
  servlet:
    context-path: /influxdb
  tomcat:
      max-threads: 1000
      min-spare-threads: 30
      uri-encoding: UTF-8

# influxDB
spring:
  influx:
    url: http://localhost:8086
    userName: root
    password: root
    database: db_demo
    retention_policy: default
    retention_policy_time: 30d