server:
  port: ${server.port}

spring:
  application:
    name: flock-center

security:
  security:
    enabled: ${security.security.enabled} # 启用身份认证
  user:
    name: ${security.user.name} # 定义用户名
    password: ${security.user.password} # 定义密码

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: ${eureka.instance.hostname}
  server:  #配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
